name: covid
data_path: /kaggle/working/labeled-chest-xray-images
preload_path: /kaggle/working/labeled-chest-xray-images_preload_data
save_path: /kaggle/working/labeled-chest-xray-images_runs
input_size: 512 # image resolution for the LPM
num_classes: 3 # number of classes
mean: [0.5] # 'auto' or a list of three numbers for RGB
std: [0.5] # 'auto' or a list of three numbers for RGB
learning_rate: 0.0005 # dataset-specific learning rate

